#!/bin/bash

echo "--- Sous Windows Agent Setup ---"
echo ""
echo "To un-hang the WSL bridge and enable the Dream Dev Setup, perform these steps on your WINDOWS host:"
echo ""
echo "1. Create a folder: C:\\tools\\sous-agent"
echo "2. Copy ALL files from 'scripts/windows/' in this repo to that folder."
echo "   (agent.ico, sous-agent.js, sous-launcher.vbs, sous-tray.ps1)"
echo ""
echo "3. Open Windows PowerShell as ADMINISTRATOR and run these commands:"
echo "   # Open the firewall"
echo "   New-NetFirewallRule -DisplayName 'Sous Agent (TCP-In)' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 4040"
echo "   New-NetFirewallRule -DisplayName 'Android ADB (TCP-In)' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 5037"
echo ""
echo "   # Unblock the script (necessary if you downloaded/copied it from the web)"
echo "   Unblock-File -Path C:\\tools\\sous-agent\\sous-tray.ps1"
echo ""
echo "4. Test the agent by double-clicking 'sous-launcher.vbs'."
echo "   You should see a Sous icon in your system tray."
echo ""
echo "5. (Optional) To run on boot:"
echo "   - Create a shortcut to 'C:\\tools\\sous-agent\\sous-launcher.vbs'"
echo "   - Press Win+R, type 'shell:startup', and paste the shortcut there."
echo ""
echo "6. Update your WSL IP in 'apps/cli/src/commands/dev/process-manager.service.ts' if it changes."
echo "   (Current detected Win IP: $(ip route show default | awk '{print $3}'))"
echo ""
echo "Once the agent is running, 'pnpm dev' will use it automatically for emulators and ADB."
