#!/bin/sh
branch=$(git branch --show-current)
if [ "$branch" = "development" ]; then
  echo "Pushing to development branch, bypassing checks."
  exit 0
fi
pnpm run lint && pnpm run typecheck && pnpm run build